#!/bin/bash

### Install all of the above pacakges ####
echo -e "Installing packages...\n"
yay -S --noconfirm hyprland kitty waybar \
swaybg wofi wlogout thunar \
ttf-jetbrains-mono-nerd noto-fonts-emoji \
ttf-font-awesome pulseaudio pavucontrol \
alsa-utils polkit-gnome python-requests \
swappy grim slurp pamixer brightnessctl gvfs \
bluez bluez-utils lxappearance xfce4-settings \
dracula-icons-git xdg-desktop-portal-hyprland-git \
btop neofetch ranger python-pillow

# Start the bluetooth service
echo -e "Starting the Bluetooth Service...\n"
sudo systemctl enable --now bluetooth.service

# Clean out other portals
echo -e "Cleaning out conflicting xdg portals...\n"
yay -R --noconfirm xdg-desktop-portal-gnome xdg-desktop-portal-gtk

### Copy Config Files ###
echo -e "Copying config files...\n"

cp -R ranger ~/.config/
cp -R kitty ~/.config/
cp -R cava ~/.config/
cp -R neofetch ~/.config/

cp -R hypr ~/.config/
cp -R waybar ~/.config/
cp -R wofi ~/.config/
cp -R wlogout ~/.config/
    
# Set some files as exacutable 
chmod +x ~/.config/hypr/xdg-portal-hyprland
chmod +x ~/.config/waybar/scripts/waybar-wttr.py

### Script is done ###
echo -e "Script had completed.\n"
