#!/bin/bash

read -rep $'Do you have an Nvidia GPU? (y,n) ' ISNVIDIA
if [[ $ISNVIDIA == "Y" || $ISNVIDIA == "y" ]]; then
    ISNVIDIA=true
else
    ISNVIDIA=false
fi
if [[ "$ISNVIDIA" == true ]]; then
    echo -e "Nvidia setup stage, this may take a while..."
    yay -S --noconfirm linux-headers nvidia-dkms qt5-wayland qt5ct libva libva-nvidia-driver-git
    sudo sed -i 's/MODULES=()/MODULES=(nvidia nvidia_modeset nvidia_uvm nvidia_drm)/' /etc/mkinitcpio.conf
    sudo mkinitcpio --config /etc/mkinitcpio.conf --generate /boot/initramfs-custom.img
    echo -e "options nvidia-drm modeset=1" | sudo tee -a /etc/modprobe.d/nvidia.conf
fi
### Install all of the above pacakges ####
yay -S --noconfirm \
hyprland kitty jq mako swww swaylock-effects \
wofi wlogout xdg-desktop-portal-hyprland-git \
swappy grim slurp polkit-gnome python-requests \
thunar pamixer pavucontrol brightnessctl gvfs \
thunar-archive-plugin file-roller btop pacman-contrib \
network-manager-applet ttf-jetbrains-mono-nerd noto-fonts-emoji \
lxappearance xfce4-settings swaybg dracula-gtk-theme dracula-icons-git xdg-desktop-portal-hyprland-git

echo -e "Installing Waybar...\n"
yay -S --noconfirm gcc12
export CC=gcc-12 CXX=g++-12
yay -S --noconfirm waybar-hyprland
    
# Clean out other portals
echo -e "Cleaning out conflicting xdg portals...\n"
yay -R --noconfirm xdg-desktop-portal-gnome xdg-desktop-portal-gtk

### Copy Config Files ###
echo -e "Copying config files...\n"
cp -R hypr ~/.config/
cp -R kitty ~/.config/
cp -R mako ~/.config/
cp -R waybar ~/.config/
cp -R swaylock ~/.config/
cp -R wofi ~/.config/
    
# Set some files as exacutable 
chmod +x ~/.config/hypr/xdg-portal-hyprland
chmod +x ~/.config/waybar/scripts/waybar-wttr.py

### Script is done ###
echo -e "Script had completed\n"
echo -e "You can start Hyprland by typing Hyprland\n"
